version: "2"

run:
  build-tags:
    - e2e
    - integration

linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - misspell
    - nakedret
    - nilerr
    - rowserrcheck
    - testifylint
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports
